### ISSUE TITLE
Problem with Character Page

### ISSUE THREAD

**Issue by MetalCar** [ApkalluFalls/apkallufalls.com#17]
I've got a problem with my character -> https://de.apkallufalls.com/character/17807309
When I getting to this page, i got several javascript errors in my developer console:
![image](https://user-images.githubusercontent.com/1355298/61289039-b1cfe380-a7c8-11e9-87ca-ed2e1ad41d18.png)

The resource, that is loaded is the url above. I don't know why this isn't working...4 hours before this worked fine.

**Comment by luminantAegis** [comment]
I am having this issue as well: https://apkallufalls.com/character/13703645/ - the console is the same, word for word.

Tested on Chrome 75.0.3770.100 and Internet Explorer 11.829.17134.0

**Comment by MetalCar** [comment]
Actually i can call my character page. @luminantAegis can you check too?

**Comment by luminantAegis** [comment]
@MetalCar I can confirm that it is working as of today.
